# Generated by Django 6.0.1 on 2026-04-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='totel_price',
            new_name='total_price',
        ),
    ]
